FROM openjdk:11  as builder

WORKDIR /app

COPY ./pom.xml /app
COPY .mvn ./.mvn
COPY mvnw .
COPY pom.xml .

RUN ./mvnw clean package -Dmaven.test.skip -Dmaven.main.skip -Dspring-boot.repackage.skip && rm -r ./target

#RUN ./mvnw dependency:go-offline

COPY ./src ./src

RUN ./mvnw clean package -DskipTests

FROM openjdk:11

WORKDIR /app

RUN mkdir ./logs

COPY --from=builder /app/target/neoris-pichincha-1.0.jar .

EXPOSE 8001

ENTRYPOINT ["java","-jar","neoris-pichincha-1.0.jar"]
